/* Connexion Two — Certificate of Completion (tamper-evident signing receipt).
 *
 * Builds a one-page PDF "proof receipt" for a signed document: title, document
 * ID, completion time, each signer (name / email / signed-at / IP / device), and
 * the document's SHA-256 fingerprint. Because the fingerprint changes if even one
 * byte of the document changes, the certificate lets anyone prove the document
 * has not been altered since it was signed.
 *
 * Requires pdf-lib (window.PDFLib) — already loaded on the signing pages:
 *   <script src="https://unpkg.com/pdf-lib/dist/pdf-lib.min.js"></script>
 *
 * Usage:
 *   const certBytes = await C2Certificate.buildPage(meta);         // standalone 1-page PDF
 *   const merged    = await C2Certificate.appendTo(pdfBytes, meta); // signed doc + cert page
 *
 * meta = {
 *   brand?: 'Connexion Two',
 *   title: 'Contractor Agreement',
 *   docId: 'uuid',
 *   completedAt?: ISO string,
 *   documentSha256: 'hex',           // fingerprint of the signed document
 *   signers: [{ order, name, email, signedAt?, ip?, userAgent? }, ...]
 * }
 */
window.C2Certificate = (function () {
  function need() { if (!window.PDFLib) throw new Error('pdf-lib (window.PDFLib) is not loaded.'); return window.PDFLib; }
  function fmt(iso) { if (!iso) return '—'; const d = new Date(iso); return isNaN(d.getTime()) ? String(iso) : d.toUTCString(); }

  async function buildCertDoc(meta) {
    const { PDFDocument, StandardFonts, rgb } = need();
    const doc  = await PDFDocument.create();
    const page = doc.addPage([595.28, 841.89]);        // A4
    const font = await doc.embedFont(StandardFonts.Helvetica);
    const bold = await doc.embedFont(StandardFonts.HelveticaBold);

    const W = 595.28, M = 48;
    const navy  = rgb(0.024, 0.102, 0.227);
    const ink   = rgb(0.07, 0.11, 0.18);
    const muted = rgb(0.37, 0.42, 0.48);
    const line  = rgb(0.85, 0.89, 0.94);
    const blue  = rgb(0, 0.33, 0.82);
    const brand = meta.brand || 'Connexion Two';
    let y = 800;

    function wrap(text, f, size, maxW) {
      const words = String(text == null ? '' : text).split(/\s+/);
      const out = []; let cur = '';
      words.forEach(w => {
        const t = cur ? cur + ' ' + w : w;
        if (f.widthOfTextAtSize(t, size) > maxW && cur) { out.push(cur); cur = w; }
        else cur = t;
      });
      if (cur) out.push(cur);
      return out.length ? out : [''];
    }
    function section(t) {
      page.drawText(t, { x: M, y, size: 10, font: bold, color: blue });
      y -= 6; page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: line }); y -= 18;
    }
    function row(label, value, opts) {
      opts = opts || {};
      page.drawText(label, { x: M, y, size: 9, font: bold, color: muted });
      const lines = wrap(value, opts.font || font, opts.size || 11, W - M - 165);
      let yy = y;
      lines.forEach((ln, i) => {
        page.drawText(ln, { x: M + 150, y: yy, size: opts.size || 11, font: opts.font || font, color: opts.color || ink });
        if (i < lines.length - 1) yy -= 14;
      });
      y = Math.min(y, yy) - 20;
    }

    // Header
    page.drawText(brand, { x: M, y, size: 12, font: bold, color: blue }); y -= 26;
    page.drawText('Certificate of Completion', { x: M, y, size: 22, font: bold, color: navy }); y -= 14;
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 1, color: line }); y -= 26;

    // Document
    section('Document');
    row('Title', meta.title || 'Untitled document', { font: bold });
    row('Document ID', meta.docId || '—');
    row('Completed (UTC)', fmt(meta.completedAt || new Date().toISOString()));
    row('Content SHA-256', meta.documentSha256 || '—', { size: 8.5 });

    // Signers
    y -= 4; section('Signers & Audit Trail');
    (meta.signers || []).forEach((s, i) => {
      page.drawText('Signer ' + (s.order || i + 1) + ':  ' + (s.name || '—'), { x: M, y, size: 11, font: bold, color: ink }); y -= 15;
      if (s.email) { page.drawText(s.email, { x: M, y, size: 9.5, font, color: muted }); y -= 13; }
      const bits = [s.signedAt ? 'Signed ' + fmt(s.signedAt) : null, s.ip ? 'IP ' + s.ip : null].filter(Boolean).join('    ·    ');
      if (bits) { page.drawText(bits, { x: M, y, size: 9, font, color: muted }); y -= 12; }
      if (s.userAgent) { wrap('Device: ' + s.userAgent, font, 8, W - 2 * M).forEach(ln => { page.drawText(ln, { x: M, y, size: 8, font, color: muted }); y -= 10; }); }
      y -= 8; page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.4, color: line }); y -= 16;
    });

    // Integrity note (pin to bottom if there's room)
    if (y > 132) y = 132;
    page.drawLine({ start: { x: M, y }, end: { x: W - M, y }, thickness: 0.5, color: line }); y -= 16;
    wrap('This certificate was generated by ' + brand + '. The Content SHA-256 above is a cryptographic fingerprint of the signed document. If any byte of the document changes, the fingerprint changes — so this value proves the document has not been altered since it was signed.', font, 8.5, W - 2 * M)
      .forEach(ln => { page.drawText(ln, { x: M, y, size: 8.5, font, color: muted }); y -= 12; });

    return doc;
  }

  async function buildPage(meta) {
    const d = await buildCertDoc(meta);
    return await d.save();
  }
  async function appendTo(pdfBytes, meta) {
    const { PDFDocument } = need();
    const src  = await PDFDocument.load(pdfBytes);
    const cert = await buildCertDoc(meta);
    const [pg] = await src.copyPages(cert, [0]);
    src.addPage(pg);
    return await src.save();
  }

  return { buildPage, appendTo };
})();
