-- Connexion Two — EU evidence & data-mapping tables
-- Run in the rfd project (rfdvogakvyodixgpvqvz) SQL editor.
--
-- These back three pages:
--   • proof-packet.html  — bundles Certificates of Completion into one Evidence Pack
--   • data-map.html      — tags documents + generates a Records of Processing report
--   • access-log.html    — shows who opened what, and when
--
-- Trust model note: like the rest of the app, the browser talks to rfd with the
-- ANON key and scopes rows client-side by owner_email (auth lives in the xbw
-- project). These policies keep that same model. Tighten later if you move auth
-- into this project.

-- ── 1) Classification tags on documents (for the Data Map / Records of Processing) ──
create table if not exists public.document_tags (
  doc_id         text primary key,
  owner_email    text,
  classification text,           -- 'none' | 'personal' | 'confidential' | 'special'
  categories     text,           -- free text: e.g. "Contact details, contract terms"
  legal_basis    text,           -- GDPR Art.6 basis, optional: e.g. "Contract (Art.6(1)(b))"
  retention      text,           -- e.g. "6 years after contract end"
  note           text,
  updated_at     timestamptz default now()
);

-- ── 2) Access / audit log (who opened or exported what) ──
create table if not exists public.access_log (
  id          bigint generated by default as identity primary key,
  doc_id      text,
  owner_email text,
  actor_email text,              -- the signed-in user who performed the action
  action      text,              -- 'view' | 'evidence_pack' | 'data_map' | 'download'
  ip          text,
  user_agent  text,
  created_at  timestamptz default now()
);
create index if not exists access_log_owner_idx on public.access_log (owner_email, created_at desc);

-- ── RLS (same permissive-but-present model the rest of the app uses) ──
alter table public.document_tags enable row level security;
alter table public.access_log   enable row level security;

drop policy if exists document_tags_all on public.document_tags;
create policy document_tags_all on public.document_tags
  for all to anon, authenticated using (true) with check (true);

drop policy if exists access_log_ins on public.access_log;
create policy access_log_ins on public.access_log
  for insert to anon, authenticated with check (true);

drop policy if exists access_log_sel on public.access_log;
create policy access_log_sel on public.access_log
  for select to anon, authenticated using (true);
