-- Connexion Two — outbound webhooks (fire an event when a document completes)
-- Run in the rfd project (rfdvogakvyodixgpvqvz) SQL editor.

-- Registered endpoints, owned per account.
create table if not exists public.webhooks (
  id          bigint generated by default as identity primary key,
  owner_email text not null,
  url         text not null,
  event       text not null default 'document.completed',  -- or '*'
  secret      text,               -- used to HMAC-sign each delivery (auto-filled if blank)
  active      boolean not null default true,
  created_at  timestamptz default now()
);
create index if not exists webhooks_owner_idx on public.webhooks (owner_email);

-- Delivery log (so the UI can show what fired and whether it succeeded).
create table if not exists public.webhook_deliveries (
  id          bigint generated by default as identity primary key,
  webhook_id  bigint,
  owner_email text,
  event       text,
  doc_id      text,
  url         text,
  status_code int,
  ok          boolean,
  error       text,
  created_at  timestamptz default now()
);
create index if not exists webhook_deliveries_owner_idx on public.webhook_deliveries (owner_email, created_at desc);

-- RLS — same permissive-but-present model as the rest of the app (client scopes
-- by owner_email; the edge function uses the service role and bypasses RLS).
alter table public.webhooks           enable row level security;
alter table public.webhook_deliveries enable row level security;

drop policy if exists webhooks_all on public.webhooks;
create policy webhooks_all on public.webhooks
  for all to anon, authenticated using (true) with check (true);

drop policy if exists webhook_deliveries_sel on public.webhook_deliveries;
create policy webhook_deliveries_sel on public.webhook_deliveries
  for select to anon, authenticated using (true);
